<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LTIN588398" failures="22" tests="88" name="Chrome Test" time="240.532" errors="0" timestamp="2025-06-02T15:18:31 IST">
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="appsMadeEnableCheck" time="0.352"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="checkWebTitle" time="0.284"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="createPortfolioBtnClickCheck" time="0.316"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="emailFieldEnableCheck" time="0.359"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="experienceFieldEnableCheck" time="0.783"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="headerCheck" time="0.351"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="jobTitleFieldEnableCheck" time="0.567"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="measureBtnClickCheck" time="0.669"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="nameFieldEnableCheck" time="0.361"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="skillsFieldEnableCheck" time="0.35"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="subTitleCheck" time="0.188"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="websitesDevelopedEnableCheck" time="0.382"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="appsMadeFieldValidationTest" time="0.304"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="appsMadeFieldValidationTest" time="0.273">
    <failure type="java.lang.AssertionError" message="Apps Made Input field is allowing Invalid input did not expect [-3] but found [-3]">
      <![CDATA[java.lang.AssertionError: Apps Made Input field is allowing Invalid input did not expect [-3] but found [-3]
at app.vercel.devProfileEight.tests.TS02_InputValidation.appsMadeFieldValidationTest(TS02_InputValidation.java:94)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- appsMadeFieldValidationTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="appsMadeFieldValidationTest" time="0.32">
    <failure type="java.lang.AssertionError" message="Apps Made Input field is allowing Invalid input did not expect [4.8] but found [4.8]">
      <![CDATA[java.lang.AssertionError: Apps Made Input field is allowing Invalid input did not expect [4.8] but found [4.8]
at app.vercel.devProfileEight.tests.TS02_InputValidation.appsMadeFieldValidationTest(TS02_InputValidation.java:94)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- appsMadeFieldValidationTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="appsMadeFieldValidationTest" time="0.275"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="appsMadeFieldValidationTest" time="0.289"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="appsMadeFieldValidationTest" time="0.297"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="appsMadeFieldValidationTest" time="0.431"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="emailFieldValidationTest" time="0.353"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="emailFieldValidationTest" time="0.364"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="emailFieldValidationTest" time="0.296"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="emailFieldValidationTest" time="0.308"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="emailFieldValidationTest" time="0.294"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.829"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.765"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.878"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="1.007"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.792"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.914"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.866"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.7"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.75"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.829"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="jobTitleFieldValidationTest" time="0.35"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="jobTitleFieldValidationTest" time="0.342"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="jobTitleFieldValidationTest" time="0.311"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.969">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.759">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.096">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.265">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="1.317"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="79.605">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="7.629">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="7.265">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.336">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="1.373"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="7.182">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.406">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.062">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="0.887"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.101">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="nameFieldValidationTest" time="0.211"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="nameFieldValidationTest" time="0.275"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="nameFieldValidationTest" time="0.26"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="nameFieldValidationTest" time="0.249"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="nameFieldValidationTest" time="0.237"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="skillsFieldValidationTest" time="0.262"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="skillsFieldValidationTest" time="0.362"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="skillsFieldValidationTest" time="0.241"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="websitesDevelopedFieldValidationTest" time="0.188"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="websitesDevelopedFieldValidationTest" time="0.203">
    <failure type="java.lang.AssertionError" message="Websites Developed Input field is allowing Invalid input did not expect [-3] but found [-3]">
      <![CDATA[java.lang.AssertionError: Websites Developed Input field is allowing Invalid input did not expect [-3] but found [-3]
at app.vercel.devProfileEight.tests.TS02_InputValidation.websitesDevelopedFieldValidationTest(TS02_InputValidation.java:76)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- websitesDevelopedFieldValidationTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="websitesDevelopedFieldValidationTest" time="0.225">
    <failure type="java.lang.AssertionError" message="Websites Developed Input field is allowing Invalid input did not expect [4.8] but found [4.8]">
      <![CDATA[java.lang.AssertionError: Websites Developed Input field is allowing Invalid input did not expect [4.8] but found [4.8]
at app.vercel.devProfileEight.tests.TS02_InputValidation.websitesDevelopedFieldValidationTest(TS02_InputValidation.java:76)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- websitesDevelopedFieldValidationTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="websitesDevelopedFieldValidationTest" time="0.217"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="websitesDevelopedFieldValidationTest" time="0.184"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="websitesDevelopedFieldValidationTest" time="0.2"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="websitesDevelopedFieldValidationTest" time="0.251"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.554">
    <failure type="java.lang.AssertionError" message="Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation.detailsEntryTestAndCreateProfile(TS03_PortfolioBtnValidation.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- detailsEntryTestAndCreateProfile -->
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.138"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="0.882"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.015"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.218"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.013"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="0.933">
    <failure type="java.lang.AssertionError" message="Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation.detailsEntryTestAndCreateProfile(TS03_PortfolioBtnValidation.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- detailsEntryTestAndCreateProfile -->
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.133"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.024"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="0.967"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="0.992"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="0.913"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.066"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.133"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.338">
    <failure type="java.lang.AssertionError" message="Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation.detailsEntryTestAndCreateProfile(TS03_PortfolioBtnValidation.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- detailsEntryTestAndCreateProfile -->
  <testcase classname="app.vercel.devProfileEight.tests.TS04_PortfolioPageValidation" name="avatarValidation" time="1.526"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS04_PortfolioPageValidation" name="avatarValidation" time="1.552"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS04_PortfolioPageValidation" name="avatarValidation" time="1.54"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS04_PortfolioPageValidation" name="backBtnValidation" time="0.263">
    <failure type="org.openqa.selenium.NoSuchElementException" message="no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;xpath&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;//a[@class=&amp;apos;btn btn-back&amp;apos;]&amp;quot;}
  (Session info: chrome=135.0.7049.96)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: &amp;apos;4.32.0&amp;apos;, revision: &amp;apos;d17c8aa950&amp;apos;
System info: os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;21.0.5&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [3ad38c34d94e619301f45f34bb68b37c, findElement {using=xpath, value=//a[@class=&amp;apos;btn btn-back&amp;apos;]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 135.0.7049.96, chrome: {chromedriverVersion: 135.0.7049.114 (63fd8a7d9d0..., userDataDir: C:\Windows\SystemTemp\scope...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:61740}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:61740/devtoo..., se:cdpVersion: 135.0.7049.96, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 3ad38c34d94e619301f45f34bb68b37c">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='btn btn-back']"}
  (Session info: chrome=135.0.7049.96)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.32.0', revision: 'd17c8aa950'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [3ad38c34d94e619301f45f34bb68b37c, findElement {using=xpath, value=//a[@class='btn btn-back']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 135.0.7049.96, chrome: {chromedriverVersion: 135.0.7049.114 (63fd8a7d9d0..., userDataDir: C:\Windows\SystemTemp\scope...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:61740}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:61740/devtoo..., se:cdpVersion: 135.0.7049.96, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 3ad38c34d94e619301f45f34bb68b37c
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:68)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy32.click(Unknown Source)
at app.vercel.devProfileEight.pageObjects.PortfolioPage.getBackButton(PortfolioPage.java:98)
at app.vercel.devProfileEight.tests.TS04_PortfolioPageValidation.backBtnValidation(TS04_PortfolioPageValidation.java:110)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- backBtnValidation -->
  <testcase classname="app.vercel.devProfileEight.tests.TS04_PortfolioPageValidation" name="backBtnValidation" time="0.097">
    <failure type="org.openqa.selenium.NoSuchElementException" message="no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;xpath&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;//a[@class=&amp;apos;btn btn-back&amp;apos;]&amp;quot;}
  (Session info: chrome=135.0.7049.96)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: &amp;apos;4.32.0&amp;apos;, revision: &amp;apos;d17c8aa950&amp;apos;
System info: os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;21.0.5&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [3ad38c34d94e619301f45f34bb68b37c, findElement {using=xpath, value=//a[@class=&amp;apos;btn btn-back&amp;apos;]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 135.0.7049.96, chrome: {chromedriverVersion: 135.0.7049.114 (63fd8a7d9d0..., userDataDir: C:\Windows\SystemTemp\scope...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:61740}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:61740/devtoo..., se:cdpVersion: 135.0.7049.96, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 3ad38c34d94e619301f45f34bb68b37c">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='btn btn-back']"}
  (Session info: chrome=135.0.7049.96)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.32.0', revision: 'd17c8aa950'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [3ad38c34d94e619301f45f34bb68b37c, findElement {using=xpath, value=//a[@class='btn btn-back']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 135.0.7049.96, chrome: {chromedriverVersion: 135.0.7049.114 (63fd8a7d9d0..., userDataDir: C:\Windows\SystemTemp\scope...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:61740}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:61740/devtoo..., se:cdpVersion: 135.0.7049.96, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 3ad38c34d94e619301f45f34bb68b37c
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:68)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy32.click(Unknown Source)
at app.vercel.devProfileEight.pageObjects.PortfolioPage.getBackButton(PortfolioPage.java:98)
at app.vercel.devProfileEight.tests.TS04_PortfolioPageValidation.backBtnValidation(TS04_PortfolioPageValidation.java:110)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- backBtnValidation -->
  <testcase classname="app.vercel.devProfileEight.tests.TS04_PortfolioPageValidation" name="backBtnValidation" time="0.087">
    <failure type="org.openqa.selenium.NoSuchElementException" message="no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;xpath&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;//a[@class=&amp;apos;btn btn-back&amp;apos;]&amp;quot;}
  (Session info: chrome=135.0.7049.96)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: &amp;apos;4.32.0&amp;apos;, revision: &amp;apos;d17c8aa950&amp;apos;
System info: os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;21.0.5&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [3ad38c34d94e619301f45f34bb68b37c, findElement {using=xpath, value=//a[@class=&amp;apos;btn btn-back&amp;apos;]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 135.0.7049.96, chrome: {chromedriverVersion: 135.0.7049.114 (63fd8a7d9d0..., userDataDir: C:\Windows\SystemTemp\scope...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:61740}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:61740/devtoo..., se:cdpVersion: 135.0.7049.96, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 3ad38c34d94e619301f45f34bb68b37c">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='btn btn-back']"}
  (Session info: chrome=135.0.7049.96)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.32.0', revision: 'd17c8aa950'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [3ad38c34d94e619301f45f34bb68b37c, findElement {using=xpath, value=//a[@class='btn btn-back']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 135.0.7049.96, chrome: {chromedriverVersion: 135.0.7049.114 (63fd8a7d9d0..., userDataDir: C:\Windows\SystemTemp\scope...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:61740}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:61740/devtoo..., se:cdpVersion: 135.0.7049.96, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 3ad38c34d94e619301f45f34bb68b37c
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:68)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy32.click(Unknown Source)
at app.vercel.devProfileEight.pageObjects.PortfolioPage.getBackButton(PortfolioPage.java:98)
at app.vercel.devProfileEight.tests.TS04_PortfolioPageValidation.backBtnValidation(TS04_PortfolioPageValidation.java:110)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- backBtnValidation -->
</testsuite> <!-- Chrome Test -->
