<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LTIN588398" failures="22" tests="88" name="Edge Test" time="177.927" errors="0" timestamp="2025-06-02T15:17:28 IST">
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="appsMadeEnableCheck" time="0.449"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="checkWebTitle" time="0.187"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="createPortfolioBtnClickCheck" time="0.554"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="emailFieldEnableCheck" time="0.494"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="experienceFieldEnableCheck" time="0.833"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="headerCheck" time="0.231"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="jobTitleFieldEnableCheck" time="0.322"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="measureBtnClickCheck" time="0.46"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="nameFieldEnableCheck" time="0.312"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="skillsFieldEnableCheck" time="0.309"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="subTitleCheck" time="0.241"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS01_HomePageValidation" name="websitesDevelopedEnableCheck" time="0.22"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="appsMadeFieldValidationTest" time="0.334"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="appsMadeFieldValidationTest" time="0.315">
    <failure type="java.lang.AssertionError" message="Apps Made Input field is allowing Invalid input did not expect [-3] but found [-3]">
      <![CDATA[java.lang.AssertionError: Apps Made Input field is allowing Invalid input did not expect [-3] but found [-3]
at app.vercel.devProfileEight.tests.TS02_InputValidation.appsMadeFieldValidationTest(TS02_InputValidation.java:94)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- appsMadeFieldValidationTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="appsMadeFieldValidationTest" time="0.456">
    <failure type="java.lang.AssertionError" message="Apps Made Input field is allowing Invalid input did not expect [4.8] but found [4.8]">
      <![CDATA[java.lang.AssertionError: Apps Made Input field is allowing Invalid input did not expect [4.8] but found [4.8]
at app.vercel.devProfileEight.tests.TS02_InputValidation.appsMadeFieldValidationTest(TS02_InputValidation.java:94)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- appsMadeFieldValidationTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="appsMadeFieldValidationTest" time="0.414"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="appsMadeFieldValidationTest" time="0.382"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="appsMadeFieldValidationTest" time="0.373"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="appsMadeFieldValidationTest" time="0.365"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="emailFieldValidationTest" time="0.333"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="emailFieldValidationTest" time="0.366"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="emailFieldValidationTest" time="0.323"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="emailFieldValidationTest" time="0.432"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="emailFieldValidationTest" time="0.324"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.833"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.502"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.682"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.656"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.62"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.727"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.714"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.879"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.68"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="experienceFieldValidationTest" time="0.464"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="jobTitleFieldValidationTest" time="0.255"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="jobTitleFieldValidationTest" time="0.213"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="jobTitleFieldValidationTest" time="0.201"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.46">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.384">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.289">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.238">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="1.013"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.204">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.116">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.041">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.412">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="0.675"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.29">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.057">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.209">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="1.212"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="measureProfileTest" time="6.292">
    <failure type="java.lang.AssertionError" message="Alert is not raised even if the details are not valid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Alert is not raised even if the details are not valid expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS02_InputValidation.measureProfileTest(TS02_InputValidation.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- measureProfileTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="nameFieldValidationTest" time="0.317"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="nameFieldValidationTest" time="0.312"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="nameFieldValidationTest" time="0.325"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="nameFieldValidationTest" time="0.32"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="nameFieldValidationTest" time="0.28"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="skillsFieldValidationTest" time="0.317"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="skillsFieldValidationTest" time="0.313"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="skillsFieldValidationTest" time="0.306"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="websitesDevelopedFieldValidationTest" time="0.333"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="websitesDevelopedFieldValidationTest" time="0.313">
    <failure type="java.lang.AssertionError" message="Websites Developed Input field is allowing Invalid input did not expect [-3] but found [-3]">
      <![CDATA[java.lang.AssertionError: Websites Developed Input field is allowing Invalid input did not expect [-3] but found [-3]
at app.vercel.devProfileEight.tests.TS02_InputValidation.websitesDevelopedFieldValidationTest(TS02_InputValidation.java:76)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- websitesDevelopedFieldValidationTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="websitesDevelopedFieldValidationTest" time="0.342">
    <failure type="java.lang.AssertionError" message="Websites Developed Input field is allowing Invalid input did not expect [4.8] but found [4.8]">
      <![CDATA[java.lang.AssertionError: Websites Developed Input field is allowing Invalid input did not expect [4.8] but found [4.8]
at app.vercel.devProfileEight.tests.TS02_InputValidation.websitesDevelopedFieldValidationTest(TS02_InputValidation.java:76)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- websitesDevelopedFieldValidationTest -->
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="websitesDevelopedFieldValidationTest" time="0.324"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="websitesDevelopedFieldValidationTest" time="0.302"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="websitesDevelopedFieldValidationTest" time="0.287"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS02_InputValidation" name="websitesDevelopedFieldValidationTest" time="0.295"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.486">
    <failure type="java.lang.AssertionError" message="Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation.detailsEntryTestAndCreateProfile(TS03_PortfolioBtnValidation.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- detailsEntryTestAndCreateProfile -->
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="2.343"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.382"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="0.96"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.446"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.858"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="2.364">
    <failure type="java.lang.AssertionError" message="Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation.detailsEntryTestAndCreateProfile(TS03_PortfolioBtnValidation.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- detailsEntryTestAndCreateProfile -->
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.417"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.22"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.007"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.958"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.489"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="0.877"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.156"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.285">
    <failure type="java.lang.AssertionError" message="Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]
at app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation.detailsEntryTestAndCreateProfile(TS03_PortfolioBtnValidation.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- detailsEntryTestAndCreateProfile -->
  <testcase classname="app.vercel.devProfileEight.tests.TS04_PortfolioPageValidation" name="avatarValidation" time="2.882"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS04_PortfolioPageValidation" name="avatarValidation" time="1.298"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS04_PortfolioPageValidation" name="avatarValidation" time="1.613"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS04_PortfolioPageValidation" name="backBtnValidation" time="0.242">
    <failure type="org.openqa.selenium.NoSuchElementException" message="no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;xpath&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;//a[@class=&amp;apos;btn btn-back&amp;apos;]&amp;quot;}
  (Session info: MicrosoftEdge=136.0.3240.92)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: &amp;apos;4.32.0&amp;apos;, revision: &amp;apos;d17c8aa950&amp;apos;
System info: os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;21.0.5&amp;apos;
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [76467a169684ebe8d43fe83f54d1b0aa, findElement {using=xpath, value=//a[@class=&amp;apos;btn btn-back&amp;apos;]}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 136.0.3240.92, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:61544}, msedge: {msedgedriverVersion: 136.0.3240.104 (6a705373902..., userDataDir: C:\Windows\SystemTemp\scope...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:61544/devtoo..., se:cdpVersion: 136.0.3240.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 76467a169684ebe8d43fe83f54d1b0aa">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='btn btn-back']"}
  (Session info: MicrosoftEdge=136.0.3240.92)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.32.0', revision: 'd17c8aa950'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.5'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [76467a169684ebe8d43fe83f54d1b0aa, findElement {using=xpath, value=//a[@class='btn btn-back']}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 136.0.3240.92, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:61544}, msedge: {msedgedriverVersion: 136.0.3240.104 (6a705373902..., userDataDir: C:\Windows\SystemTemp\scope...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:61544/devtoo..., se:cdpVersion: 136.0.3240.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 76467a169684ebe8d43fe83f54d1b0aa
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:68)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy32.click(Unknown Source)
at app.vercel.devProfileEight.pageObjects.PortfolioPage.getBackButton(PortfolioPage.java:98)
at app.vercel.devProfileEight.tests.TS04_PortfolioPageValidation.backBtnValidation(TS04_PortfolioPageValidation.java:110)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- backBtnValidation -->
  <testcase classname="app.vercel.devProfileEight.tests.TS04_PortfolioPageValidation" name="backBtnValidation" time="0.208">
    <failure type="org.openqa.selenium.NoSuchElementException" message="no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;xpath&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;//a[@class=&amp;apos;btn btn-back&amp;apos;]&amp;quot;}
  (Session info: MicrosoftEdge=136.0.3240.92)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: &amp;apos;4.32.0&amp;apos;, revision: &amp;apos;d17c8aa950&amp;apos;
System info: os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;21.0.5&amp;apos;
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [76467a169684ebe8d43fe83f54d1b0aa, findElement {using=xpath, value=//a[@class=&amp;apos;btn btn-back&amp;apos;]}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 136.0.3240.92, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:61544}, msedge: {msedgedriverVersion: 136.0.3240.104 (6a705373902..., userDataDir: C:\Windows\SystemTemp\scope...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:61544/devtoo..., se:cdpVersion: 136.0.3240.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 76467a169684ebe8d43fe83f54d1b0aa">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='btn btn-back']"}
  (Session info: MicrosoftEdge=136.0.3240.92)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.32.0', revision: 'd17c8aa950'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.5'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [76467a169684ebe8d43fe83f54d1b0aa, findElement {using=xpath, value=//a[@class='btn btn-back']}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 136.0.3240.92, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:61544}, msedge: {msedgedriverVersion: 136.0.3240.104 (6a705373902..., userDataDir: C:\Windows\SystemTemp\scope...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:61544/devtoo..., se:cdpVersion: 136.0.3240.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 76467a169684ebe8d43fe83f54d1b0aa
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:68)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy32.click(Unknown Source)
at app.vercel.devProfileEight.pageObjects.PortfolioPage.getBackButton(PortfolioPage.java:98)
at app.vercel.devProfileEight.tests.TS04_PortfolioPageValidation.backBtnValidation(TS04_PortfolioPageValidation.java:110)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- backBtnValidation -->
  <testcase classname="app.vercel.devProfileEight.tests.TS04_PortfolioPageValidation" name="backBtnValidation" time="0.151">
    <failure type="org.openqa.selenium.NoSuchElementException" message="no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;xpath&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;//a[@class=&amp;apos;btn btn-back&amp;apos;]&amp;quot;}
  (Session info: MicrosoftEdge=136.0.3240.92)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: &amp;apos;4.32.0&amp;apos;, revision: &amp;apos;d17c8aa950&amp;apos;
System info: os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;21.0.5&amp;apos;
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [76467a169684ebe8d43fe83f54d1b0aa, findElement {using=xpath, value=//a[@class=&amp;apos;btn btn-back&amp;apos;]}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 136.0.3240.92, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:61544}, msedge: {msedgedriverVersion: 136.0.3240.104 (6a705373902..., userDataDir: C:\Windows\SystemTemp\scope...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:61544/devtoo..., se:cdpVersion: 136.0.3240.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 76467a169684ebe8d43fe83f54d1b0aa">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='btn btn-back']"}
  (Session info: MicrosoftEdge=136.0.3240.92)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.32.0', revision: 'd17c8aa950'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.5'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [76467a169684ebe8d43fe83f54d1b0aa, findElement {using=xpath, value=//a[@class='btn btn-back']}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 136.0.3240.92, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:61544}, msedge: {msedgedriverVersion: 136.0.3240.104 (6a705373902..., userDataDir: C:\Windows\SystemTemp\scope...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:61544/devtoo..., se:cdpVersion: 136.0.3240.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 76467a169684ebe8d43fe83f54d1b0aa
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:68)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy32.click(Unknown Source)
at app.vercel.devProfileEight.pageObjects.PortfolioPage.getBackButton(PortfolioPage.java:98)
at app.vercel.devProfileEight.tests.TS04_PortfolioPageValidation.backBtnValidation(TS04_PortfolioPageValidation.java:110)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- backBtnValidation -->
</testsuite> <!-- Edge Test -->
