<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LTIN588398" failures="6" tests="30" name="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" time="39.364" errors="0" timestamp="2025-06-02T15:18:31 IST" skipped="0">
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="2.384"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="0.981"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.295">
    <failure message="Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation.detailsEntryTestAndCreateProfile(TS03_PortfolioBtnValidation.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- detailsEntryTestAndCreateProfile -->
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="0.987"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.483"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="2.379">
    <failure message="Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation.detailsEntryTestAndCreateProfile(TS03_PortfolioBtnValidation.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- detailsEntryTestAndCreateProfile -->
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.875"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.235"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.152"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.575">
    <failure message="Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation.detailsEntryTestAndCreateProfile(TS03_PortfolioBtnValidation.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- detailsEntryTestAndCreateProfile -->
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.185"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.044"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="0.935"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.157"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.041"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.514">
    <failure message="Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation.detailsEntryTestAndCreateProfile(TS03_PortfolioBtnValidation.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- detailsEntryTestAndCreateProfile -->
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.088"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.524"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.075"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.421"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.994"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.450"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="0.890"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.150"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="0.965">
    <failure message="Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation.detailsEntryTestAndCreateProfile(TS03_PortfolioBtnValidation.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- detailsEntryTestAndCreateProfile -->
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.233"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="0.912"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.360">
    <failure message="Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Invalid details entered still creating portifolio and navigating to portifolio page expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation.detailsEntryTestAndCreateProfile(TS03_PortfolioBtnValidation.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- detailsEntryTestAndCreateProfile -->
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.022"/>
  <testcase classname="app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation" name="detailsEntryTestAndCreateProfile" time="1.058"/>
</testsuite> <!-- app.vercel.devProfileEight.tests.TS03_PortfolioBtnValidation -->
